{{/*
Expand the name of the chart.
*/}}
{{- define "nexus.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Create a fully qualified app name (truncated to 63 chars to satisfy DNS-1123).
*/}}
{{- define "nexus.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Chart label.
*/}}
{{- define "nexus.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Common labels applied to every object.
*/}}
{{- define "nexus.labels" -}}
helm.sh/chart: {{ include "nexus.chart" . }}
{{ include "nexus.selectorLabels" . }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/part-of: nexus
{{- end -}}

{{/*
Selector labels — must remain stable across upgrades; do not include
the chart version here.
*/}}
{{- define "nexus.selectorLabels" -}}
app.kubernetes.io/name: {{ include "nexus.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}

{{/*
Service account name resolution.
*/}}
{{- define "nexus.serviceAccountName" -}}
{{- if .Values.serviceAccount.create -}}
{{- default (include "nexus.fullname" .) .Values.serviceAccount.name -}}
{{- else -}}
{{- default "default" .Values.serviceAccount.name -}}
{{- end -}}
{{- end -}}

{{/*
Resolve the image reference. Falls back to `.Chart.AppVersion` when
the user did not pin a tag — the chart and the binary version then
move in lockstep.
*/}}
{{- define "nexus.image" -}}
{{- $tag := default .Chart.AppVersion .Values.image.tag -}}
{{- printf "%s:%s" .Values.image.repository $tag -}}
{{- end -}}

{{/*
Headless service name — required for StatefulSet pod DNS, and used by
the Raft peer discovery in cluster mode.
*/}}
{{- define "nexus.headlessServiceName" -}}
{{- printf "%s-headless" (include "nexus.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Effective replica count — `replicaCount` in standalone, otherwise
`numShards * replicaFactor` in cluster mode.
*/}}
{{- define "nexus.replicas" -}}
{{- if eq .Values.mode "cluster" -}}
{{- mul (int .Values.cluster.numShards) (int .Values.cluster.replicaFactor) -}}
{{- else -}}
{{- .Values.replicaCount -}}
{{- end -}}
{{- end -}}

{{/*
Name of the auth Secret. Either user-supplied (`auth.root.existingSecret`)
or generated by the chart's templates/secret.yaml.
*/}}
{{- define "nexus.authSecretName" -}}
{{- if .Values.auth.root.existingSecret -}}
{{- .Values.auth.root.existingSecret -}}
{{- else -}}
{{- printf "%s-auth" (include "nexus.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}

{{/*
Name of the ConfigMap holding `config.yml` (when provided).
*/}}
{{- define "nexus.configMapName" -}}
{{- printf "%s-config" (include "nexus.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Compose the comma-separated peer list consumed by NEXUS_SHARDING_PEERS.
Each pod gets a deterministic id derived from its ordinal (`shard-N-replica-M`
is overkill for the chart; we keep it simple with `nexus-N`). The pod's own
id is filtered out by the server's bootstrap layer.
*/}}
{{- define "nexus.shardingPeers" -}}
{{- $svc := include "nexus.headlessServiceName" . -}}
{{- $ns := .Release.Namespace -}}
{{- $port := .Values.cluster.raftPort -}}
{{- $count := int (include "nexus.replicas" .) -}}
{{- $peers := list -}}
{{- range $i, $_ := until $count -}}
{{- $peer := printf "node-%d=%s-%d.%s.%s.svc.cluster.local:%d" $i (include "nexus.fullname" $) $i $svc $ns $port -}}
{{- $peers = append $peers $peer -}}
{{- end -}}
{{- join "," $peers -}}
{{- end -}}
