{{- if and .Values.auth.enabled .Values.auth.root.enabled (not .Values.auth.root.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexus.authSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.auth.root.username | quote }}
  password: {{ .Values.auth.root.password | default (randAlphaNum 32) | quote }}
{{- end -}}
