apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.targetPort }}
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.http.nodePort }}
      nodePort: {{ .Values.service.http.nodePort }}
      {{- end }}
    {{- if .Values.server.rpc.enabled }}
    - name: rpc
      port: {{ .Values.service.rpc.port }}
      targetPort: {{ .Values.service.rpc.targetPort }}
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.rpc.nodePort }}
      nodePort: {{ .Values.service.rpc.nodePort }}
      {{- end }}
    {{- end }}
    {{- if .Values.server.resp3.enabled }}
    - name: resp3
      port: {{ .Values.server.resp3.port }}
      targetPort: {{ .Values.server.resp3.port }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "nexus.selectorLabels" . | nindent 4 }}
