"""Official Python SDK for Nexus graph database."""

from nexus_sdk.client import NexusClient
from nexus_sdk.error import NexusError
from nexus_sdk.models import (
    QueryResult,
    DatabaseStats,
    Node,
    Relationship,
    CreateNodeRequest,
    CreateNodeResponse,
    UpdateNodeRequest,
    UpdateNodeResponse,
    DeleteNodeRequest,
    DeleteNodeResponse,
    CreateRelationshipRequest,
    CreateRelationshipResponse,
    UpdateRelationshipRequest,
    UpdateRelationshipResponse,
    DeleteRelationshipRequest,
    DeleteRelationshipResponse,
    LabelInfo,
    LabelResponse,
    RelTypeInfo,
    RelTypeResponse,
    TransactionResponse,
    Value,
    BatchNode,
    BatchRelationship,
    BatchCreateNodesResponse,
    BatchCreateRelationshipsResponse,
    QueryStatisticsResponse,
    SlowQueriesResponse,
    PlanCacheStatisticsResponse,
    # Database management models
    DatabaseInfo,
    ListDatabasesResponse,
    CreateDatabaseRequest,
    CreateDatabaseResponse,
    DropDatabaseResponse,
    SessionDatabaseResponse,
    SwitchDatabaseRequest,
    SwitchDatabaseResponse,
)
from nexus_sdk.query_builder import QueryBuilder
from nexus_sdk.transaction import Transaction, TransactionStatus
from nexus_sdk.transport import (
    Endpoint,
    NexusValue,
    Transport,
    TransportCredentials,
    TransportMode,
    default_local_endpoint,
    parse_endpoint,
)

__version__ = "1.0.0"
__all__ = [
    "NexusClient",
    "NexusError",
    "QueryResult",
    "DatabaseStats",
    "Node",
    "Relationship",
    "CreateNodeRequest",
    "CreateNodeResponse",
    "UpdateNodeRequest",
    "UpdateNodeResponse",
    "DeleteNodeRequest",
    "DeleteNodeResponse",
    "CreateRelationshipRequest",
    "CreateRelationshipResponse",
    "UpdateRelationshipRequest",
    "UpdateRelationshipResponse",
    "DeleteRelationshipRequest",
    "DeleteRelationshipResponse",
    "LabelInfo",
    "LabelResponse",
    "RelTypeInfo",
    "RelTypeResponse",
    "TransactionResponse",
    "Value",
    "BatchNode",
    "BatchRelationship",
    "BatchCreateNodesResponse",
    "BatchCreateRelationshipsResponse",
    "QueryStatisticsResponse",
    "SlowQueriesResponse",
    "PlanCacheStatisticsResponse",
    "QueryBuilder",
    "Transaction",
    "TransactionStatus",
    # Database management
    "DatabaseInfo",
    "ListDatabasesResponse",
    "CreateDatabaseRequest",
    "CreateDatabaseResponse",
    "DropDatabaseResponse",
    "SessionDatabaseResponse",
    "SwitchDatabaseRequest",
    "SwitchDatabaseResponse",
    # Transport layer
    "Endpoint",
    "NexusValue",
    "Transport",
    "TransportCredentials",
    "TransportMode",
    "default_local_endpoint",
    "parse_endpoint",
]
