#!/usr/bin/env python3
"""Migrate a Kùzu CSV / Parquet export into a Nexus database.

Architecture
------------

The script has two execution modes, controlled by `--mode`:

* **load-csv**: emits a `LOAD CSV WITH HEADERS` Cypher driver script
  per table under `--out-dir`. Apply with `nexus query` (or any
  SDK). Suitable up to ~10M rows per table; trivial to inspect by
  hand.
* **bulk-rpc**: streams the CSV into a running Nexus server via the
  Python SDK's `batch_create_nodes` / `batch_create_relationships`
  helpers. Suitable for arbitrarily large inputs.

Both modes accept the same CLI for table → file mapping. Node tables
use `--node Label:path.csv`. Relationship tables use
`--rel SrcLabel-TYPE-DstLabel:path.csv` and require the export to
include `from` and `to` columns referencing the upstream node IDs.

Cypher dialect translation
--------------------------

The `--rewrite-cypher` subcommand reads a file of Kùzu Cypher
queries and rewrites the three Kùzu-isms documented in
`docs/migration/FROM_KUZU.md` to their Nexus equivalents:

* `[*SHORTEST n..m]` → `shortestPath(...)` wrapper.
* `CALL CREATE_HNSW_INDEX(...)` → `CALL db.knn.create(...)`.
* `CALL QUERY_VECTOR_INDEX(...)` → `CALL db.knn.search(...)` plus
  the cosine-similarity sign flip.
* `CALL CREATE_FTS_INDEX(...)` / `CALL QUERY_FTS_INDEX(...)` →
  `db.index.fulltext.createNodeIndex` / `queryNodes`.

The translator intentionally errs on the side of leaving unfamiliar
input untouched and emitting a `-- TRANSLATOR-NOTE: ...` comment so
the operator can review.
"""

from __future__ import annotations

import argparse
import csv
import dataclasses
import re
import sys
from pathlib import Path
from typing import Iterable, Iterator, Optional

# Schema mapping
# --------------

KUZU_TYPE_MAP: dict[str, str] = {
    "STRING": "string",
    "INT8": "integer",
    "INT16": "integer",
    "INT32": "integer",
    "INT64": "integer",
    "UINT8": "integer",
    "UINT16": "integer",
    "UINT32": "integer",
    "UINT64": "integer",
    "FLOAT": "float",
    "DOUBLE": "float",
    "BOOL": "boolean",
    "DATE": "date",
    "TIMESTAMP": "datetime",
    "INTERVAL": "duration",
    "BLOB": "bytes",
}


@dataclasses.dataclass(frozen=True)
class NodeSpec:
    label: str
    csv_path: Path

    @classmethod
    def parse(cls, raw: str) -> "NodeSpec":
        if ":" not in raw:
            raise ValueError(
                f"--node expects 'Label:path.csv', got {raw!r}"
            )
        label, _, path = raw.partition(":")
        if not label or not path:
            raise ValueError(
                f"--node expects 'Label:path.csv', got {raw!r}"
            )
        return cls(label=label, csv_path=Path(path))


@dataclasses.dataclass(frozen=True)
class RelSpec:
    src_label: str
    rel_type: str
    dst_label: str
    csv_path: Path

    @classmethod
    def parse(cls, raw: str) -> "RelSpec":
        # Format: SrcLabel-TYPE-DstLabel:path.csv
        if ":" not in raw:
            raise ValueError(
                f"--rel expects 'SrcLabel-TYPE-DstLabel:path.csv', got {raw!r}"
            )
        head, _, path = raw.partition(":")
        parts = head.split("-")
        if len(parts) != 3 or not all(parts) or not path:
            raise ValueError(
                f"--rel expects 'SrcLabel-TYPE-DstLabel:path.csv', got {raw!r}"
            )
        src, rel_type, dst = parts
        return cls(
            src_label=src,
            rel_type=rel_type,
            dst_label=dst,
            csv_path=Path(path),
        )


# Cypher emission
# ---------------

def emit_load_csv_node(spec: NodeSpec, id_property: str = "id") -> str:
    return (
        f"// {spec.csv_path}\n"
        f"LOAD CSV WITH HEADERS FROM 'file:///{spec.csv_path.as_posix()}' AS row\n"
        f"MERGE (n:{spec.label} {{ {id_property}: row.{id_property} }})\n"
        f"SET n += apoc.map.removeKey(row, '{id_property}');\n"
    )


def emit_load_csv_rel(spec: RelSpec, id_property: str = "id") -> str:
    return (
        f"// {spec.csv_path}\n"
        f"LOAD CSV WITH HEADERS FROM 'file:///{spec.csv_path.as_posix()}' AS row\n"
        f"MATCH (a:{spec.src_label} {{ {id_property}: row.from }}),\n"
        f"      (b:{spec.dst_label} {{ {id_property}: row.to   }})\n"
        f"MERGE (a)-[r:{spec.rel_type}]->(b)\n"
        f"SET r += apoc.map.removeKey(apoc.map.removeKey(row, 'from'), 'to');\n"
    )


def write_load_csv_driver(
    out_dir: Path,
    nodes: list[NodeSpec],
    rels: list[RelSpec],
    id_property: str,
) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / "load.cypher"
    with target.open("w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/migration/from_kuzu.py\n")
        f.write("// Apply with: nexus query --file load.cypher\n\n")
        for node in nodes:
            f.write(emit_load_csv_node(node, id_property=id_property))
            f.write("\n")
        # Always create node-id indexes before loading relationships.
        if nodes:
            f.write("// Indexes for fast relationship matching\n")
            for label in sorted({n.label for n in nodes}):
                f.write(
                    f"CREATE INDEX {label.lower()}_{id_property} "
                    f"IF NOT EXISTS FOR (n:{label}) ON (n.{id_property});\n"
                )
            f.write("\n")
        for rel in rels:
            f.write(emit_load_csv_rel(rel, id_property=id_property))
            f.write("\n")
    return target


# CSV streaming
# -------------

def stream_node_rows(
    spec: NodeSpec, id_property: str = "id"
) -> Iterator[tuple[list[str], dict[str, str]]]:
    """Yield (labels, properties) tuples from a Kùzu node CSV."""
    with spec.csv_path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            properties = {k: v for k, v in row.items() if v is not None}
            yield [spec.label], properties


def stream_rel_rows(
    spec: RelSpec, id_property: str = "id"
) -> Iterator[tuple[str, str, str, dict[str, str]]]:
    """Yield (src_id, dst_id, rel_type, properties) tuples from a rel CSV."""
    with spec.csv_path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        if "from" not in reader.fieldnames or "to" not in reader.fieldnames:
            raise ValueError(
                f"{spec.csv_path}: relationship CSVs must have "
                f"'from' and 'to' columns (got {reader.fieldnames})"
            )
        for row in reader:
            src = row.pop("from")
            dst = row.pop("to")
            properties = {k: v for k, v in row.items() if v is not None}
            yield src, dst, spec.rel_type, properties


# Cypher dialect translation
# --------------------------

# `[*SHORTEST n..m]` → `shortestPath((...)-[*n..m]-(...))`.
SHORTEST_RE = re.compile(
    r"\[\s*(?P<binding>\w+)?\s*\*\s*SHORTEST\s+(?P<lo>\d+)\.\.(?P<hi>\d+)\s*\]"
)
HNSW_CREATE_RE = re.compile(
    r"CALL\s+CREATE_HNSW_INDEX\s*\(\s*"
    r"'(?P<label>[^']+)'\s*,\s*"
    r"'(?P<index_name>[^']+)'\s*,\s*"
    r"'(?P<column>[^']+)'\s*"
    r"(?P<rest>[^)]*)\)\s*;?",
    re.IGNORECASE,
)
HNSW_QUERY_RE = re.compile(
    r"CALL\s+QUERY_VECTOR_INDEX\s*\(\s*"
    r"'(?P<label>[^']+)'\s*,\s*"
    r"'(?P<index_name>[^']+)'\s*,\s*"
    r"(?P<query>[^,]+)\s*,\s*"
    r"(?P<k>\d+)\s*\)",
    re.IGNORECASE,
)
FTS_CREATE_RE = re.compile(
    r"CALL\s+CREATE_FTS_INDEX\s*\(\s*"
    r"'(?P<label>[^']+)'\s*,\s*"
    r"'(?P<index_name>[^']+)'\s*,\s*"
    r"\[(?P<columns>[^\]]+)\]\s*"
    r"(?P<rest>[^)]*)\)\s*;?",
    re.IGNORECASE,
)
FTS_QUERY_RE = re.compile(
    r"CALL\s+QUERY_FTS_INDEX\s*\(\s*"
    r"'(?P<label>[^']+)'\s*,\s*"
    r"'(?P<index_name>[^']+)'\s*,\s*"
    r"(?P<query>[^)]+)\)",
    re.IGNORECASE,
)


def translate_cypher(query: str) -> tuple[str, list[str]]:
    """Translate Kùzu-flavoured Cypher to Nexus.

    Returns the rewritten query plus a list of human-readable notes
    summarising every transformation applied. Unknown constructs are
    left unchanged and surfaced in the notes so the operator can
    review.
    """
    notes: list[str] = []
    out = query

    def shortest_replace(match: re.Match[str]) -> str:
        notes.append(
            f"rewrote [*SHORTEST {match.group('lo')}..{match.group('hi')}]"
            f" to shortestPath() — review surrounding pattern"
        )
        # Keep the original numeric range; the surrounding `MATCH p =`
        # template is the operator's responsibility per the docs.
        return f"[*{match.group('lo')}..{match.group('hi')}]"

    out = SHORTEST_RE.sub(shortest_replace, out)

    def hnsw_create_replace(match: re.Match[str]) -> str:
        notes.append(
            "rewrote CREATE_HNSW_INDEX to db.knn.create — confirm "
            "vector dimension matches your data"
        )
        rest = match.group("rest").strip().lstrip(",").strip()
        params = _parse_kuzu_kwargs(rest)
        m = params.get("mu") or params.get("M") or "16"
        efc = params.get("efc") or params.get("efConstruction") or "200"
        return (
            f"CALL db.knn.create('{match.group('label')}', "
            f"'{match.group('column')}', $dim, "
            f"{{ M: {m}, efConstruction: {efc}, efSearch: 50 }}) "
            f"YIELD name"
        )

    out = HNSW_CREATE_RE.sub(hnsw_create_replace, out)

    def hnsw_query_replace(match: re.Match[str]) -> str:
        notes.append(
            "rewrote QUERY_VECTOR_INDEX to db.knn.search — note that "
            "Nexus returns cosine SIMILARITY (higher=closer); flip "
            "any ORDER BY distance ASC to score DESC"
        )
        return (
            f"CALL db.knn.search('{match.group('label')}', "
            f"'embedding', {match.group('query').strip()}, "
            f"{match.group('k')}) YIELD node, score"
        )

    out = HNSW_QUERY_RE.sub(hnsw_query_replace, out)

    def fts_create_replace(match: re.Match[str]) -> str:
        notes.append("rewrote CREATE_FTS_INDEX to db.index.fulltext.createNodeIndex")
        return (
            f"CALL db.index.fulltext.createNodeIndex("
            f"'{match.group('index_name')}', "
            f"['{match.group('label')}'], "
            f"[{match.group('columns')}])"
        )

    out = FTS_CREATE_RE.sub(fts_create_replace, out)

    def fts_query_replace(match: re.Match[str]) -> str:
        notes.append("rewrote QUERY_FTS_INDEX to db.index.fulltext.queryNodes")
        return (
            f"CALL db.index.fulltext.queryNodes("
            f"'{match.group('index_name')}', {match.group('query').strip()}) "
            f"YIELD node, score"
        )

    out = FTS_QUERY_RE.sub(fts_query_replace, out)
    return out, notes


def _parse_kuzu_kwargs(rest: str) -> dict[str, str]:
    """Parse `key1 := value1, key2 := value2` Kùzu kwarg syntax."""
    out: dict[str, str] = {}
    if not rest:
        return out
    for pair in rest.split(","):
        if ":=" not in pair:
            continue
        k, _, v = pair.partition(":=")
        out[k.strip()] = v.strip()
    return out


# CLI
# ---

def _make_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Migrate a Kùzu export into Nexus."
    )
    sub = parser.add_subparsers(dest="command", required=True)

    load = sub.add_parser(
        "load-csv",
        help="Emit LOAD CSV driver script(s) under --out-dir.",
    )
    load.add_argument("--node", action="append", default=[], help="Label:path.csv")
    load.add_argument("--rel", action="append", default=[], help="Src-TYPE-Dst:path.csv")
    load.add_argument("--out-dir", type=Path, default=Path("migrated"))
    load.add_argument("--id-property", default="id")

    bulk = sub.add_parser(
        "bulk-rpc",
        help="Stream the CSV into a running Nexus server via the SDK.",
    )
    bulk.add_argument("--node", action="append", default=[], help="Label:path.csv")
    bulk.add_argument("--rel", action="append", default=[], help="Src-TYPE-Dst:path.csv")
    bulk.add_argument(
        "--target",
        default="nexus://localhost:15475",
        help="Nexus RPC URL (default: nexus://localhost:15475).",
    )
    bulk.add_argument("--batch-size", type=int, default=10_000)
    bulk.add_argument("--dry-run", action="store_true")

    rewrite = sub.add_parser(
        "rewrite-cypher",
        help="Translate Kùzu-flavoured Cypher to Nexus Cypher.",
    )
    rewrite.add_argument("input", type=Path)
    rewrite.add_argument("--output", type=Path)

    return parser


def main(argv: Optional[Iterable[str]] = None) -> int:
    args = _make_parser().parse_args(list(argv) if argv is not None else None)

    if args.command == "load-csv":
        nodes = [NodeSpec.parse(s) for s in args.node]
        rels = [RelSpec.parse(s) for s in args.rel]
        target = write_load_csv_driver(args.out_dir, nodes, rels, args.id_property)
        print(f"[from-kuzu] wrote {target}")
        return 0

    if args.command == "bulk-rpc":
        nodes = [NodeSpec.parse(s) for s in args.node]
        rels = [RelSpec.parse(s) for s in args.rel]
        return _run_bulk_rpc(args, nodes, rels)

    if args.command == "rewrite-cypher":
        text = args.input.read_text(encoding="utf-8")
        translated, notes = translate_cypher(text)
        out = args.output if args.output else None
        if out:
            with out.open("w", encoding="utf-8") as f:
                if notes:
                    for note in notes:
                        f.write(f"-- TRANSLATOR-NOTE: {note}\n")
                f.write(translated)
            print(f"[from-kuzu] wrote {out} ({len(notes)} note(s))")
        else:
            for note in notes:
                print(f"-- TRANSLATOR-NOTE: {note}", file=sys.stderr)
            sys.stdout.write(translated)
        return 0

    return 2


def _run_bulk_rpc(
    args: argparse.Namespace,
    nodes: list[NodeSpec],
    rels: list[RelSpec],
) -> int:
    if args.dry_run:
        node_count = sum(_count_csv_rows(n.csv_path) for n in nodes)
        rel_count = sum(_count_csv_rows(r.csv_path) for r in rels)
        print(
            f"[from-kuzu] dry run: would ingest {node_count} nodes "
            f"and {rel_count} relationships into {args.target} "
            f"(batch_size={args.batch_size})"
        )
        return 0

    try:
        import asyncio

        from nexus_sdk import NexusClient
    except ImportError as exc:
        print(
            f"[from-kuzu] bulk-rpc requires hivehub-nexus-sdk: {exc}",
            file=sys.stderr,
        )
        return 1

    async def run() -> int:
        async with NexusClient(args.target) as client:
            for node in nodes:
                await _ingest_nodes(client, node, args.batch_size)
            for rel in rels:
                await _ingest_rels(client, rel, args.batch_size)
        return 0

    return asyncio.run(run())


def _count_csv_rows(path: Path) -> int:
    with path.open("r", encoding="utf-8", newline="") as f:
        # subtract the header row
        return max(0, sum(1 for _ in f) - 1)


async def _ingest_nodes(client, spec: NodeSpec, batch_size: int) -> None:
    batch: list[dict] = []
    total = 0
    for labels, properties in stream_node_rows(spec):
        batch.append({"labels": labels, "properties": properties})
        if len(batch) >= batch_size:
            await client.batch_create_nodes(batch)
            total += len(batch)
            batch.clear()
    if batch:
        await client.batch_create_nodes(batch)
        total += len(batch)
    print(f"[from-kuzu] ingested {total} {spec.label} nodes from {spec.csv_path}")


async def _ingest_rels(client, spec: RelSpec, batch_size: int) -> None:
    batch: list[dict] = []
    total = 0
    for src, dst, rel_type, properties in stream_rel_rows(spec):
        batch.append(
            {
                "source_id": int(src),
                "target_id": int(dst),
                "rel_type": rel_type,
                "properties": properties,
            }
        )
        if len(batch) >= batch_size:
            await client.batch_create_relationships(batch)
            total += len(batch)
            batch.clear()
    if batch:
        await client.batch_create_relationships(batch)
        total += len(batch)
    print(
        f"[from-kuzu] ingested {total} {spec.rel_type} "
        f"relationships from {spec.csv_path}"
    )


if __name__ == "__main__":
    sys.exit(main())
